version: '3'
services:
  db:
    image: 'postgres:10'
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: myblog
      POSTGRES_USER: myblog
      POSTGRES_PASSWORD: myblog

  web:
    build: .
    depends_on:
      - db
    ports:
      - '3001:3001'
    volumes:
      - .:/project
    restart: on-failure
    environment:
      DATABASE_URL: postgres://myblog:myblog@db:5432/myblog
      PORT: 3001
