name:                myblog
version:             0.1.0.0
github:              "willisplummer/myblog"
license:             BSD3
author:              "willis plummer"
maintainer:          "willisplummer@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/willisplummer/myblog#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bcrypt
- bytestring
- hlint
- monad-logger
- mtl
- persistent
- persistent-template
- persistent-postgresql
- resource-pool
- servant
- servant-auth
- servant-auth-server
- servant-server
- string-conversions
- text
- transformers
- wai
- warp

library:
  source-dirs: src

executables:
  run-server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - myblog

  migrate-db:
    main:                MigrateDB.hs
    source-dirs:         app
    ghc-options:
    - -main-is
    - MigrateDB
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - myblog

tests:
  myblog-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - myblog
