jobs:
  build:
    machine: true
    steps:
      - checkout

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run: docker pull willisplummer/haskell-blog:firsttry

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build . -t willisplummer/haskell-blog:$TAG
          docker push willisplummer/haskell-blog:$TAG
