version: 2

jobs:
  build:
    docker:
      - image: haskell:8.4.3

    steps:
      - checkout

      - run:
          name: setup
          command: stack setup

      - run:
          name: build
          command: stack build

      - run:
          name: test
          command: stack test
